#!/usr/bin/env bash


pushd "$(dirname $0)" > /dev/null
export MAIN_ROOT_DIR="$(pwd)"
popd > /dev/null

if [ ! -d "$MAIN_ROOT_DIR/.build" ]; then
  mkdir -v "$MAIN_ROOT_DIR/.build"
fi

if [ ! -f "$MAIN_ROOT_DIR/.build/build.ninja" ]; then
  if [ "$1" != "" ]; then
    BUILD_TYPE="$1"
  else
    BUILD_TYPE="release"
  fi
  meson --buildtype "$BUILD_TYPE" "$MAIN_ROOT_DIR" "$MAIN_ROOT_DIR/.build"
  if [ "$?" != "0" ]; then
    exit 1
  fi
fi

ninja -C "$MAIN_ROOT_DIR/.build"
