#!/usr/bin/env bash
## Usage: build [ninja_arguments]

## Zisti absolutnú cestu ku skriptu a nastav prostredie pomocou `bash-env.sh`.
## Predpokladá sa, že skript je v podadresári `src/main` gitovského repozitára.
pushd "$(dirname $0)" > /dev/null
export MAIN_ROOT_DIR="$(pwd)"
popd > /dev/null
source ${MAIN_ROOT_DIR}/bash-env.sh

## Zaisti, že existuje adresár na kompiláciu projektu.
if [ ! -d "$MAIN_BUILD_DIR" ]; then
  mkdir -v "$MAIN_BUILD_DIR"
fi

## Vygeneruj kompilačné pravidlá pri prvej kompilácii.
if [ ! -f "${MAIN_BUILD_DIR}/build.ninja" ]; then
  ## Skontroluj závislosti.
  ## Možno obísť manuálne ak meson nie je v $PATH lebo si pamätá odkiaľ sa volal.
  if [ -z "$HAS_MESON" ]; then
    echo "Missing build dependency: meson"
    exit 1
  fi
  if [ -z "$HAS_NINJA" ]; then
    echo "Missing build dependency: ninja-build"
    exit 1
  fi

  meson --buildtype release "$MAIN_ROOT_DIR" "$MAIN_BUILD_DIR"
  if [ "$?" != "0" ]; then
    exit 1
  fi
fi

## Skompiluj projekt a posuň prípadné argumenty ninjovi
ninja -C "$MAIN_BUILD_DIR" $@
