#!/usr/bin/env bash

pushd "$(dirname $0)" > /dev/null
export MAIN_ROOT_DIR="$(pwd)"
popd > /dev/null
source "$MAIN_ROOT_DIR/bash-env.sh"

clean_logs

spawn server
check_alive

spawn border
spawn pheromone
spawn base
spawn food
spawn ant

spawn visualisation

stop

sleep 1s
print_performance