#!/usr/bin/env bash

pushd "$(dirname $0)" > /dev/null
export MAIN_ROOT_DIR="$(pwd)"
popd > /dev/null
source "$MAIN_ROOT_DIR/bash-env.sh"


spawn server
check_alive

spawn border
spawn line

spawn visualisation

stop
