#!/usr/bin/env bash

function spawn
{
  name="$1"
  shift
  pushd "$name/bin" > /dev/null
  if [ "$?" == "0" ]; then
    ./main.elf $@ &
    echo "$(basename $0): Spawned $name with PID $!"
    popd > /dev/null
  else
    echo "$(basename $0): Target '$name' does not exist"
    exit 1
  fi
}


spawn server

sleep 1s
pgrep main.elf > /dev/null
if [ "$?" == "1" ]; then
  echo "$(basename $0): Server crashed"
  echo "$(basename $0): Aborting"
  exit 1
fi

spawn visualisation

spawn border

spawn base
spawn food
spawn food
spawn pheromone
spawn ant
