#!/usr/bin/env bash

pushd "$(dirname $0)" > /dev/null
export MAIN_ROOT_DIR="$(pwd)"
popd > /dev/null
source "$MAIN_ROOT_DIR/bash-env.sh"


spawn server
check_alive

spawn mode_bot

#security border
spawn border

#line follower
spawn line

#sumo arena
spawn arena

#ants demo
spawn pheromone
spawn base
spawn food
spawn ant

spawn visualisation

stop
